version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./data:/app/data
    command: npm run start
    ports:
      - 5009:5009
    environment:
      - PORT=5009
      - WEBAPP_PORT=5009
      - OPENAI_API_KEY=${OPENAI_API_KEY}